services:
  arima_worker:
    image: duongtm3102/ml_worker:v3
    container_name: arima_worker
    environment:
      DB_URL: "mysql+pymysql://root:Uet123@mysql/iotdata"
      HOUSE_IDS_TO_FORECAST: 0,5,20
      SLICE_GAP: 5
      FORECAST_INTERVAL: 1
      RETRAIN_INTERVAL: 30
    networks:
     - stormsmarthome_storm_network
    restart: always
    labels:
        autoheal: True
    healthcheck:
      test: "python worker/healthcheck.py ARIMA 5"
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 600s

  xgboost_worker:
    image: duongtm3102/ml_worker:v3
    container_name: xgboost_worker
    command: python worker/xgboost_model.py
    environment:
      DB_URL: "mysql+pymysql://root:Uet123@mysql/iotdata"
      HOUSE_IDS_TO_FORECAST: 0,5,20
      SLICE_GAP: 5
      FORECAST_INTERVAL: 1
      RETRAIN_INTERVAL: 30
    networks:
     - stormsmarthome_storm_network
    restart: always
    labels:
        autoheal: True
    healthcheck:
      test: "python worker/healthcheck.py XGBoost 5"
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 600s
  neuralprophet_worker:
    image: duongtm3102/ml_worker:v2.5
    container_name: neuralprophet_worker
    command: python worker/neuralprophet_model.py
    environment:
      DB_URL: "mysql+pymysql://root:Uet123@mysql/iotdata"
      HOUSE_IDS_TO_FORECAST: 0,5,20
      SLICE_GAP: 5
      FORECAST_INTERVAL: 1
      RETRAIN_INTERVAL: 30
    networks:
     - stormsmarthome_storm_network
    restart: always
    labels:
        autoheal: True
    healthcheck:
      test: "python worker/healthcheck.py NeuralProphet 5"
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 600s
  
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  stormsmarthome_storm_network:
    external: true
    
    
